### ISSUE TITLE
Замечания ДЗ

### ISSUE THREAD

**Issue by ananasn** [Trolljeger/ITMO_repo#1]
* Задание 1 выполнено неверно. "Начиная с 6 символа" не означает, что у символа индекс 6, потому что индексация начинается с 0.

**Comment by Trolljeger** [comment]
Исправлено. Но думаю стоит точнее формулировать.
В задании 1 указано, что нумерация от 0. Соответственно, в первом решении вывод осуществлялся с 6 символа в нумерации от 0 (7-й в нумерации от 1).
